services:
  linkloom:
    image: nandolawson/linkloom:latest
    container_name: linkloom
    restart: always
    ports:
      - 5500:80/tcp
    volumes:
      - config:/srv/config
    deploy:
      resources:
        limits:
          memory: 128M
    healthcheck:
      test: ["CMD", "wget", "--spider", "--timeout=10", "http://localhost:80"]
      interval: 30s
      timeout: 10s
      retries: 3
    logging:
      driver: "json-file"
      options:
        max-size: 10m
        max-file: 3
volumes:
  config:
    name: linkloom-config