services:
  linkloom:
    image: nandolawson/linkloom:latest
    restart: unless-stopped
    ports:
      - 5500:80/tcp
    volumes:
      - linkloom:/srv/config:rw
    deploy:
      resources:
        limits:
          memory: 128M
    logging:
      driver: "json-file"
      options:
        max-size: 10m
        max-file: 3
volumes:
  linkloom:
    external: false