services:
  linkloom:
    image: nandolawson/linkloom:latest
    container_name: linkloom
    restart: always
    ports:
      - 5500:80/tcp
    volumes:
      - ./config:/srv/config
    deploy:
      resources:
        limits:
          memory: 128M
    logging:
      driver: "json-file"
      options:
        max-size: 10m
        max-file: 3